// flow-typed signature: a5044f8f878a183d83cc6182a7b3cae1
// flow-typed version: <<STUB>>/jsrsasign_v^8.0.6/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsrsasign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsrsasign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsrsasign/lib/footer' {
  declare module.exports: any;
}

declare module 'jsrsasign/lib/header' {
  declare module.exports: any;
}

declare module 'jsrsasign/lib/jsrsasign-all-min' {
  declare module.exports: any;
}

declare module 'jsrsasign/lib/jsrsasign-jwths-min' {
  declare module.exports: any;
}

declare module 'jsrsasign/lib/jsrsasign-rsa-min' {
  declare module.exports: any;
}

declare module 'jsrsasign/lib/jsrsasign' {
  declare module.exports: any;
}

declare module 'jsrsasign/lib/lib' {
  declare module.exports: any;
}

declare module 'jsrsasign/test/t_base64x' {
  declare module.exports: any;
}

declare module 'jsrsasign/test/t_rsasign' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsrsasign/lib/footer.js' {
  declare module.exports: $Exports<'jsrsasign/lib/footer'>;
}
declare module 'jsrsasign/lib/header.js' {
  declare module.exports: $Exports<'jsrsasign/lib/header'>;
}
declare module 'jsrsasign/lib/jsrsasign-all-min.js' {
  declare module.exports: $Exports<'jsrsasign/lib/jsrsasign-all-min'>;
}
declare module 'jsrsasign/lib/jsrsasign-jwths-min.js' {
  declare module.exports: $Exports<'jsrsasign/lib/jsrsasign-jwths-min'>;
}
declare module 'jsrsasign/lib/jsrsasign-rsa-min.js' {
  declare module.exports: $Exports<'jsrsasign/lib/jsrsasign-rsa-min'>;
}
declare module 'jsrsasign/lib/jsrsasign.js' {
  declare module.exports: $Exports<'jsrsasign/lib/jsrsasign'>;
}
declare module 'jsrsasign/lib/lib.js' {
  declare module.exports: $Exports<'jsrsasign/lib/lib'>;
}
declare module 'jsrsasign/test/t_base64x.js' {
  declare module.exports: $Exports<'jsrsasign/test/t_base64x'>;
}
declare module 'jsrsasign/test/t_rsasign.js' {
  declare module.exports: $Exports<'jsrsasign/test/t_rsasign'>;
}
