// flow-typed signature: 67f830118efd07fb90cf98b92b261c00
// flow-typed version: <<STUB>>/pg-format_v^1.0.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg-format/lib/index' {
  declare module.exports: any;
}

declare module 'pg-format/lib/reserved' {
  declare module.exports: any;
}

declare module 'pg-format/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg-format/lib/index.js' {
  declare module.exports: $Exports<'pg-format/lib/index'>;
}
declare module 'pg-format/lib/reserved.js' {
  declare module.exports: $Exports<'pg-format/lib/reserved'>;
}
declare module 'pg-format/test/index.js' {
  declare module.exports: $Exports<'pg-format/test/index'>;
}
