// flow-typed signature: b5a660c9aaf3c434b74f9f7250fe1f9f
// flow-typed version: <<STUB>>/plaid_v2.3.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plaid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plaid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plaid/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'plaid/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'plaid/lib/plaid' {
  declare module.exports: any;
}

declare module 'plaid/lib/PlaidClient' {
  declare module.exports: any;
}

declare module 'plaid/lib/plaidEnvironments' {
  declare module.exports: any;
}

declare module 'plaid/lib/plaidRequest' {
  declare module.exports: any;
}

declare module 'plaid/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plaid/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'plaid/coverage/lcov-report/prettify'>;
}
declare module 'plaid/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'plaid/coverage/lcov-report/sorter'>;
}
declare module 'plaid/lib/plaid.js' {
  declare module.exports: $Exports<'plaid/lib/plaid'>;
}
declare module 'plaid/lib/PlaidClient.js' {
  declare module.exports: $Exports<'plaid/lib/PlaidClient'>;
}
declare module 'plaid/lib/plaidEnvironments.js' {
  declare module.exports: $Exports<'plaid/lib/plaidEnvironments'>;
}
declare module 'plaid/lib/plaidRequest.js' {
  declare module.exports: $Exports<'plaid/lib/plaidRequest'>;
}
declare module 'plaid/test.js' {
  declare module.exports: $Exports<'plaid/test'>;
}
