// flow-typed signature: 6b1dfe3b4434c02c9fbb8a23c8b3600a
// flow-typed version: <<STUB>>/thebugger_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thebugger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'thebugger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'thebugger/index' {
  declare module.exports: $Exports<'thebugger'>;
}
declare module 'thebugger/index.js' {
  declare module.exports: $Exports<'thebugger'>;
}
